# Generated by Django 3.2.9 on 2021-11-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='Slider_images/')),
                ('image2', models.ImageField(upload_to='Slider_images/')),
                ('image3', models.ImageField(upload_to='Slider_images/')),
            ],
        ),
    ]
