# Generated by Django 3.2.9 on 2021-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211107_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='image3',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='name',
            field=models.CharField(default='image', max_length=20),
            preserve_default=False,
        ),
    ]
