# Generated by Django 3.2.9 on 2021-11-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211123_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_item',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.product'),
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='itemname',
            field=models.CharField(default='cookie', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='price',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
