# Generated by Django 3.2.9 on 2021-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='detail_filled',
            field=models.BooleanField(default=False),
        ),
    ]
