# Generated by Django 3.2.9 on 2021-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_detail_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='detail_filled',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_city',
            field=models.CharField(default='pokhara', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_road',
            field=models.CharField(default='2nd roaad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='sumit', max_length=30),
            preserve_default=False,
        ),
    ]
